config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

  root to: "tops#home"

  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :follows, :followers, :posts
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    collection do
      get :confirm, :search
    end

    member do
      patch :publish
    end

    resources :comments, only: [:create, :destroy]
    resources :categories, only: [:index, :show]
  end

  get '/manifest.json', to: redirect('/assets/manifest.json')
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
      current_user.follow(params[:user_id])
      redirect_to request.referer
  end
    
  def destroy
      current_user.unfollow(params[:user_id])
      redirect_to request.referer
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/create.js.erb
// @user のフォロワー数のみ更新
document.getElementById("followers-count").innerHTML = 
  `<%= j link_to "#{@user.followers.count}人", followers_user_path(@user) %>`;

// ボタンを「フォローを外す」に変更
document.getElementById("follow-button").innerHTML = 
  `<%= j button_to "フォローを外す", relationship_path(@relationship), 
                  method: :delete, remote: true, class: "btn btn-danger", data: { turbo: false } %>`;

app/views/relationships/destroy.js.erb
// current_user のフォロー数を更新
document.getElementById("followings-count").innerHTML = 
  `<%= j link_to "#{current_user.followings.count}人", followings_user_path(current_user) %>`;

// @user のフォロワー数を更新
document.getElementById("followers-count").innerHTML = 
  `<%= j link_to "#{@user.followers.count}人", followers_user_path(@user) %>`;

// ボタンを「フォローする」に変更
document.getElementById("follow-button").innerHTML = 
  `<%= j button_to "フォローする", relationships_path(followed_id: @user.id), 
                  method: :post, remote: true, class: "btn btn-primary", data: { turbo: false } %>`;